# -*- coding: utf-8 -*-
"""DATA CLEANING AND PREPROCESSING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RFVjpRtCyOjrm4Xu5ykNnVVWBjs_hEji
"""

IMPORTING THE DATA SET

# Commented out IPython magic to ensure Python compatibility.
# import the required Python libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

data

""" **DATA PRE-PROCESSING**"""

# Remove the 'index' column

data.drop( columns = 'index', inplace = True)

data

# Get some Info about the dataset

data.info()

data.isnull().sum()            # check for the missing values in any column

# Checking how many Airlines are in the dataset

data['airline'].nunique()

# Showing the names of the Airlines in the dataset

data['airline'].unique()