# -*- coding: utf-8 -*-
"""DOCUMENTATION,INSIGHTS&PRESENTATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vL3zmshSzmbE3qD7Mjca0KQ_EDExODqo

**Key Insights the indian flight dataset result**

1. Pricing Factors: Ticket prices generally increase with the number of stops and decrease the further in advance they are booked.

2.Airline & Price: Vistara frequently represents the higher-end, premium, or business class, contributing to higher average fares.

3.Duration & Cost: A linear relationship exists between flight duration and price; longer journeys with more stops are generally more expensive.

4.Travel Times: Morning departures are frequent but may not be the most economical; early morning flights often offer lower prices.

5.Popular Routes: High-density routes (e.g., Delhi-Mumbai) see significant competition among carriers like IndiGo and Air India, impacting pricing.

6.Data Structure: The dataset typically includes cabin class (Economy/Business), total stops, operator, and time-based features, making it suitable for regression analysis and price prediction.

**Indian flight data set finding's**

1.Best Time to Book: Booking closer to the departure date results in significantly higher costs (last-minute surge).

2.Top Airlines: Major operators in the data include Indigo, Air India, Vistara, and SpiceJet.

3.Impact of Class: Business class, often dominated by Vistara, significantly drives up the average ticket cost compared to economy.

4.Busiest Routes (Jan 2026): Mumbai-Delhi (BOM-DEL) is the busiest, followed by Bengaluru-Delhi (BLR-DEL).

5.Airport Growth: Delhi (DEL) remains the busiest, with a 10% increase in capacity, while Kolkata (CCU) and Hyderabad (HYD) saw a 4% contraction.

6.Traffic Projections: Domestic passenger traffic is expected to grow six-fold to 1.1 billion by 2040, with the commercial fleet expanding significantly.

7.International Market Share: In 2024, Air India led international traffic (23.6%), followed by IndiGo (17.6%) and Emirates (8.3%)

8.Ticket Pricing: Based on analyzed datasets, the average domestic ticket price is approximately ₹9,048, with significant variations based on stops and routes.

9.Operational Data: Datasets (2018-2025) track technical faults, flight delays, cancellations, and passenger impact, particularly between 2022 and 2024.

10.Customer Sentiment: Customer reviews (from Skytrax) reveal insights into satisfaction and areas for improvement for various carriers.

**Conclusion of Indian flight dataset**

Analysis of the Indian flight dataset reveals that ticket pricing is heavily influenced by airline, route, and booking time, with Indigo demonstrating superior operational efficiency through high aircraft utilization. Key factors like, stops, and departure times significantly affect fares. The findings suggest optimizing booking times and improving route efficiency are crucial for better traveler experience and revenue management.
"""