# -*- coding: utf-8 -*-
"""Exploratory data analysis and visualization's.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JK8ce82CkKYP7pr1EjahTcsSmZ4JwvgA

**EXPLORATARY DATA AND ANALYSIS (EDA)**
"""

# Get Statistical summary about the dataset

data.describe()

data[ data['duration'] == 49.830000 ]

data[ data['duration'] == 0.830000 ]

data [ data['price'] == 123071.000000 ]

data [ data['price'] == 1105.000000 ]

"""# **VISUALIZATION'S**

# **Show Bar plot's representing the Departure Time & Arrival Time`**
"""

# Showing all the Airlines with their frequencies

data['airline'].value_counts()

# Showing all the Airlines with their Number of Flights in Horizontal Bar Graph

data['airline'].value_counts(ascending=True).plot.barh( color = ['lightgreen', 'lightblue'])

plt.title("Airlines with frequencies")

plt.xlabel(" Number of flights")

plt.ylabel(" Airlines")

plt.show()

data.head()

# Showing the Departure Time for the flights

data['departure_time'].value_counts()

# Showing the Arrival Time for the flights

data['arrival_time'].value_counts()

# Showing the Departure Time & Arrival Time for the flights with their counts

plt.figure(figsize = (16,4))

plt.subplot(1,2,1)

plt.bar( data['departure_time'].value_counts().index , data['departure_time'].value_counts().values, color = ['r', 'b'] )
plt.title("Departure Time")
plt.xlabel("D. Time")
plt.ylabel("D. Freq")

plt.subplot(1,2,2)

plt.bar( data['arrival_time'].value_counts().index, data['arrival_time'].value_counts().values, color = ['g', 'y'])
plt.title("Arrival Time")
plt.xlabel("A. Time")
plt.ylabel("A. Freq")

plt.show()

"""**Showing Bar plot's representing the Source City & Destination City**"""

data.head()

# Showing the Source City of the flights

data['source_city'].value_counts()

# Showing the Destination City of the flights

data['destination_city'].value_counts()

# Showing the Source City & Destination City for the flights with their counts

plt.figure( figsize= (16,4))

plt.subplot(1,2,1)

plt.barh( data['source_city'].value_counts().index , data['source_city'].value_counts().values, color = ['m', 'g'])
plt.title("Source Cities with No. of flights")
plt.ylabel("Cities")
plt.xlabel("No. of flights")

plt.subplot(1,2,2)

plt.barh( data['destination_city'].value_counts().index , data['destination_city'].value_counts().values, color = ['y', 'r'])
plt.title("Destination Cities with No. of flights")
plt.ylabel("Cities")
plt.xlabel("No. of flights")

plt.show()

"""**BAR PLOT'S AND LINE CHART**"""

data.head()

# Checking the Mean Ticket Price based on the Departure Times

data.groupby('departure_time')['price'].mean()

# Checking the Mean Ticket Price based on the Arrival Times

data.groupby('arrival_time')['price'].mean()

sns.catplot( x = 'departure_time', y = 'price', kind = 'bar', data = data )

plt.show()

sns.catplot( x = 'arrival_time', y = 'price', kind = 'bar', data = data )

plt.show()

sns.relplot( x = 'arrival_time', y = 'price', data = data, col = 'departure_time', kind = 'line')

plt.show()

"""**The price changes with change in Source and Destination**"""

data.head()

# Checking the Mean Ticket Price for each Source City

data.groupby('source_city')['price'].mean()

# Checking the Mean Ticket Price for each Destination City

data.groupby('destination_city')['price'].mean()

sns.relplot( x = 'destination_city', y = 'price', data = data, col = "source_city", kind = 'line')

plt.show()

"""The price affected when tickets are bought in just 1 or 2 days before departure`"""

data.head()

data['days_left'].nunique()

data['days_left'].unique()

# the Mean Ticket Price for different days_left

data.groupby('days_left')['price'].mean()

sns.relplot( y='price', x = 'days_left', kind = 'line', data = data )

plt.show()